Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sympy import *
y=x**3-2*x+100
x=Symbol('x')
y.diff(x)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-1-d7e0870e17e3>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mfrom[0m [0msympy[0m [1;32mimport[0m [1;33m*[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0my[0m[1;33m=[0m[0mx[0m[1;33m**[0m[1;36m3[0m[1;33m-[0m[1;36m2[0m[1;33m*[0m[0mx[0m[1;33m+[0m[1;36m100[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mx[0m[1;33m=[0m[0mSymbol[0m[1;33m([0m[1;34m'x'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0my[0m[1;33m.[0m[0mdiff[0m[1;33m([0m[0mx[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'x' is not defined
NameError: name 'x' is not defined

